In [2]:
!pip install numpy

In [3]:
import numpy as np 
data = np.arange(64).reshape((4, 4, 4))
data

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11],
        [12, 13, 14, 15]],

       [[16, 17, 18, 19],
        [20, 21, 22, 23],
        [24, 25, 26, 27],
        [28, 29, 30, 31]],

       [[32, 33, 34, 35],
        [36, 37, 38, 39],
        [40, 41, 42, 43],
        [44, 45, 46, 47]],

       [[48, 49, 50, 51],
        [52, 53, 54, 55],
        [56, 57, 58, 59],
        [60, 61, 62, 63]]])

In [23]:
window = data[:, 0 * 2: 0 * 2 + 2,
                    0 * 2: 0 * 2 + 2]
print(window)
np.unravel_index(np.argmax(window, axis=None), window.shape)

[[[ 0  1]
  [ 4  5]]

 [[16 17]
  [20 21]]

 [[32 33]
  [36 37]]

 [[48 49]
  [52 53]]]


(3, 1, 1)

In [25]:
pip install --upgrade numpy


You should consider upgrading via the 'c:\Users\raufi\Rauf\ailab\task\taks 01\myenv\Scripts\python.exe -m pip install --upgrade pip' command.


In [4]:
import numpy as np

# Assuming 'window' is your 4x2x2 numpy array
# Example data for illustration purposes
window = np.random.rand(2, 6, 6)
window

array([[[0.96544236, 0.07309796, 0.31129709, 0.10397638, 0.86476894,
         0.24700296],
        [0.37068969, 0.46501924, 0.35858827, 0.01684642, 0.67230861,
         0.06914669],
        [0.85287551, 0.16571751, 0.32967244, 0.10419659, 0.06332369,
         0.96779483],
        [0.32325857, 0.12316132, 0.84011364, 0.54330212, 0.76266258,
         0.39978015],
        [0.27895132, 0.54374555, 0.35227654, 0.10182928, 0.22213657,
         0.51770409],
        [0.56241546, 0.63988748, 0.23612217, 0.44636222, 0.35637826,
         0.77357873]],

       [[0.9126444 , 0.63451918, 0.0391769 , 0.31138616, 0.33791011,
         0.60188661],
        [0.89892477, 0.64715395, 0.3777247 , 0.81375882, 0.35721205,
         0.47326813],
        [0.77547179, 0.47382499, 0.45992266, 0.56805465, 0.95361259,
         0.0289416 ],
        [0.85494557, 0.273516  , 0.99503349, 0.60605855, 0.96365593,
         0.80588987],
        [0.43888826, 0.1140822 , 0.51755334, 0.78552164, 0.20798558,
         0.96784514

In [10]:
arr = np.ones((2, 2))

In [11]:
window[:, 1:3, 1:3] = arr

In [12]:
window

array([[[0.96544236, 0.07309796, 0.31129709, 0.10397638, 0.86476894,
         0.24700296],
        [0.37068969, 1.        , 1.        , 0.01684642, 0.67230861,
         0.06914669],
        [0.85287551, 1.        , 1.        , 0.10419659, 0.06332369,
         0.96779483],
        [0.32325857, 0.12316132, 0.84011364, 0.54330212, 0.76266258,
         0.39978015],
        [0.27895132, 0.54374555, 0.35227654, 0.10182928, 0.22213657,
         0.51770409],
        [0.56241546, 0.63988748, 0.23612217, 0.44636222, 0.35637826,
         0.77357873]],

       [[0.9126444 , 0.63451918, 0.0391769 , 0.31138616, 0.33791011,
         0.60188661],
        [0.89892477, 1.        , 1.        , 0.81375882, 0.35721205,
         0.47326813],
        [0.77547179, 1.        , 1.        , 0.56805465, 0.95361259,
         0.0289416 ],
        [0.85494557, 0.273516  , 0.99503349, 0.60605855, 0.96365593,
         0.80588987],
        [0.43888826, 0.1140822 , 0.51755334, 0.78552164, 0.20798558,
         0.96784514